// frontend/src/components/evals/InputFileSelector.tsx
import { useState, useEffect } from "react";
import { HTTP_BACKEND_URL } from "../../config";
import { BsCheckLg, BsChevronDown, BsChevronRight } from "react-icons/bs";
import { Button } from "../ui/button";

interface InputFile {
  name: string;
  path: string;
}

interface InputFileSelectorProps {
  onFilesSelected: (files: string[]) => void;
}

function InputFileSelector({ onFilesSelected }: InputFileSelectorProps) {
  const [inputFiles, setInputFiles] = useState<InputFile[]>([]);
  const [selectedFiles, setSelectedFiles] = useState<string[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [isExpanded, setIsExpanded] = useState(false);
  
  useEffect(() => {
    fetchInputFiles();
  }, []);

  const fetchInputFiles = async () => {
    setIsLoading(true);
    try {
      const response = await fetch(`${HTTP_BACKEND_URL}/eval_input_files`);
      if (!response.ok) {
        throw new Error("获取输入文件失败");
      }
      
      const data = await response.json();
      setInputFiles(data);
      
      // By default, select all files
      const allFilePaths = data.map((file: InputFile) => file.path);
      setSelectedFiles(allFilePaths);
      onFilesSelected(allFilePaths);
    } catch (error) {
      console.error("Error fetching input files:", error);
    } finally {
      setIsLoading(false);
    }
  };

  const handleFileToggle = (filePath: string) => {
    setSelectedFiles((prev) => {
      const newSelection = prev.includes(filePath)
        ? prev.filter((path) => path !== filePath)
        : [...prev, filePath];
      
      onFilesSelected(newSelection);
      return newSelection;
    });
  };

  const handleSelectAll = () => {
    const allFilePaths = inputFiles.map((file) => file.path);
    setSelectedFiles(allFilePaths);
    onFilesSelected(allFilePaths);
  };

  const handleClearAll = () => {
    setSelectedFiles([]);
    onFilesSelected([]);
  };

  const toggleExpanded = () => {
    setIsExpanded(!isExpanded);
  };

  if (isLoading) {
    return <div className="text-center text-sm text-gray-500">正在加载输入文件...</div>;
  }

  const fileCount = inputFiles.length;
  const selectedCount = selectedFiles.length;

  return (
    <div className="w-full">
      <div 
        className="flex items-center justify-between cursor-pointer hover:bg-gray-50 rounded-md p-2 mb-2 border" 
        onClick={toggleExpanded}
      >
        <div className="flex items-center gap-2">
          {isExpanded ? <BsChevronDown className="text-gray-500" /> : <BsChevronRight className="text-gray-500" />}
          <div>
            <span className="text-sm font-medium">输入文件</span>
            <span className="ml-2 text-xs text-gray-500">
              已选 {selectedCount} / {fileCount}
            </span>
          </div>
        </div>
        
        <div className="flex space-x-1" onClick={(e) => e.stopPropagation()}>
          <Button
            variant="ghost"
            size="sm"
            onClick={handleSelectAll}
            className="text-xs h-6 px-2 text-gray-500 hover:text-gray-700"
            disabled={selectedCount === fileCount}
          >
            全选
          </Button>
          <Button
            variant="ghost"
            size="sm"
            onClick={handleClearAll}
            className="text-xs h-6 px-2 text-gray-500 hover:text-gray-700"
            disabled={selectedCount === 0}
          >
            全不选
          </Button>
        </div>
      </div>
      
      {isExpanded && (
        <div className="border rounded-md overflow-hidden">
          <div className="max-h-48 overflow-y-auto">
            <div className="grid grid-cols-1 divide-y divide-gray-100">
              {inputFiles.map((file) => (
                <div
                  key={file.path}
                  className={`flex items-center justify-between px-3 py-1.5 cursor-pointer hover:bg-gray-50 ${
                    selectedFiles.includes(file.path)
                      ? "bg-blue-50"
                      : ""
                  }`}
                  onClick={() => handleFileToggle(file.path)}
                >
                  <span className="text-xs truncate pr-2" title={file.name}>
                    {file.name}
                  </span>
                  {selectedFiles.includes(file.path) ? (
                    <BsCheckLg className="h-3 w-3 text-blue-500 flex-shrink-0" />
                  ) : (
                    <div className="h-3 w-3 border rounded-sm flex-shrink-0" />
                  )}
                </div>
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default InputFileSelector;

// frontend/src/components/evals/InputFileSelector.vue
<template>
  <div class="w-full">
    <div
      class="flex items-center justify-between cursor-pointer hover:bg-gray-50 rounded-md p-2 mb-2 border"
      @click="toggleExpanded"
    >
      <div class="flex items-center gap-2">
        <span class="text-gray-500">
          <svg
            v-if="isExpanded"
            class="h-4 w-4"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
          </svg>
          <svg
            v-else
            class="h-4 w-4"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
          </svg>
        </span>
        <div>
          <span class="text-sm font-medium">输入文件</span>
          <span class="ml-2 text-xs text-gray-500">已选 {{ selectedCount }} / {{ fileCount }}</span>
        </div>
      </div>
      <div class="flex space-x-1" @click.stop>
        <button
          type="button"
          class="text-xs h-6 px-2 text-gray-500 hover:text-gray-700"
          :disabled="selectedCount === fileCount"
          @click="handleSelectAll"
        >
          全选
        </button>
        <button
          type="button"
          class="text-xs h-6 px-2 text-gray-500 hover:text-gray-700"
          :disabled="selectedCount === 0"
          @click="handleClearAll"
        >
          全不选
        </button>
      </div>
    </div>

    <div v-if="isLoading" class="text-center text-sm text-gray-500">正在加载输入文件...</div>

    <div v-else-if="isExpanded" class="border rounded-md overflow-hidden">
      <div class="max-h-48 overflow-y-auto">
        <div class="grid grid-cols-1 divide-y divide-gray-100">
          <div
            v-for="file in inputFiles"
            :key="file.path"
            class="flex items-center justify-between px-3 py-1.5 cursor-pointer hover:bg-gray-50"
            :class="selectedFiles.includes(file.path) ? 'bg-blue-50' : ''"
            @click="handleFileToggle(file.path)"
          >
            <span class="text-xs truncate pr-2" :title="file.name">{{ file.name }}</span>
            <span v-if="selectedFiles.includes(file.path)" class="text-blue-500">
              <svg class="h-3 w-3" viewBox="0 0 24 24" fill="currentColor">
                <path d="M20 6L9 17l-5-5 1.4-1.4L9 14.2 18.6 4.6 20 6z" />
              </svg>
            </span>
            <span v-else class="h-3 w-3 border rounded-sm" />
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { HTTP_BACKEND_URL } from "../../config";

interface InputFile {
  name: string;
  path: string;
}

const emit = defineEmits<{ (e: "files-selected", files: string[]): void }>();

const inputFiles = ref<InputFile[]>([]);
const selectedFiles = ref<string[]>([]);
const isLoading = ref(false);
const isExpanded = ref(false);

const fileCount = computed(() => inputFiles.value.length);
const selectedCount = computed(() => selectedFiles.value.length);

const fetchInputFiles = async () => {
  isLoading.value = true;
  try {
    const response = await fetch(`${HTTP_BACKEND_URL}/eval_input_files`);
    if (!response.ok) {
      throw new Error("获取输入文件失败");
    }

    const data = await response.json();
    inputFiles.value = data;

    const allFilePaths = data.map((file: InputFile) => file.path);
    selectedFiles.value = allFilePaths;
    emit("files-selected", allFilePaths);
  } catch (error) {
    console.error("Error fetching input files:", error);
  } finally {
    isLoading.value = false;
  }
};

onMounted(() => {
  fetchInputFiles();
});

const handleFileToggle = (filePath: string) => {
  if (selectedFiles.value.includes(filePath)) {
    selectedFiles.value = selectedFiles.value.filter((path) => path !== filePath);
  } else {
    selectedFiles.value = [...selectedFiles.value, filePath];
  }
  emit("files-selected", selectedFiles.value);
};

const handleSelectAll = () => {
  const allFilePaths = inputFiles.value.map((file) => file.path);
  selectedFiles.value = allFilePaths;
  emit("files-selected", allFilePaths);
};

const handleClearAll = () => {
  selectedFiles.value = [];
  emit("files-selected", []);
};

const toggleExpanded = () => {
  isExpanded.value = !isExpanded.value;
};
</script>
