// frontend/src/components/evals/RunEvalsPage.tsx
import { useState, useEffect } from "react";
import { Button } from "../ui/button";
import { HTTP_BACKEND_URL } from "../../config";
import { BsCheckLg, BsChevronDown, BsChevronRight } from "react-icons/bs";
import InputFileSelector from "./InputFileSelector";
import EvalNavigation from "./EvalNavigation";

interface ModelResponse {
  models: string[];
  stacks: string[];
}

function RunEvalsPage() {
  const [isRunning, setIsRunning] = useState(false);
  const [models, setModels] = useState<string[]>([]);
  const [stacks, setStacks] = useState<string[]>([]);
  const [selectedModels, setSelectedModels] = useState<string[]>([]);
  const [selectedStack, setSelectedStack] = useState<string>("html_tailwind");
  const [selectedFiles, setSelectedFiles] = useState<string[]>([]);
  const [showPaths, setShowPaths] = useState<boolean>(false);

  useEffect(() => {
    const fetchModels = async () => {
      const response = await fetch(`${HTTP_BACKEND_URL}/models`);
      const data: ModelResponse = await response.json();
      setModels(data.models);
      setStacks(data.stacks);
    };
    fetchModels();
  }, []);

  useEffect(() => {
    return () => {
      document.title = "截图生成代码";
    };
  }, []);

  const runEvals = async () => {
    try {
      setIsRunning(true);
      document.title = "正在运行评测...";

      const response = await fetch(`${HTTP_BACKEND_URL}/run_evals`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          models: selectedModels,
          stack: selectedStack,
          files: selectedFiles,
        }),
      });

      if (!response.ok) {
        throw new Error("运行评测失败");
      }

      const outputFiles = await response.json();
      console.log("Generated files:", outputFiles);

      document.title = "✓ 评测完成";
    } catch (error) {
      console.error("Error running evals:", error);
      document.title = "❌ 评测错误";
      setTimeout(() => {
        document.title = "截图生成代码";
      }, 5000);
    } finally {
      setIsRunning(false);
    }
  };

  const handleModelToggle = (model: string) => {
    setSelectedModels((prev) => {
      if (prev.includes(model)) {
        return prev.filter((m) => m !== model);
      }
      return [...prev, model];
    });
  };

  const handleSelectAll = () => {
    setSelectedModels(models);
  };

  const handleFilesSelected = (files: string[]) => {
    setSelectedFiles(files);
  };

  // Format model list for display in the summary
  const formatModelList = () => {
    if (selectedModels.length === 0) return "无";
    if (selectedModels.length === 1) return selectedModels[0];
    if (selectedModels.length <= 2) return selectedModels.join(", ");
    return `${selectedModels.slice(0, 2).join(", ")} +${selectedModels.length - 2} 个`;
  };

  const canRunEvals = selectedModels.length > 0 && selectedFiles.length > 0;

  return (
    <div>
      <EvalNavigation />
      
      <div className="container mx-auto px-4 py-6">
        {/* Unified Header with Configuration Summary */}
        <div className="mb-6 bg-white rounded-lg border border-gray-200 shadow-sm p-4 max-w-5xl mx-auto">
          <div className="flex flex-col gap-4">
            <div className="flex flex-wrap justify-between items-center">
              <h1 className="text-2xl font-bold">运行评测</h1>
              
              <Button
                onClick={runEvals}
                disabled={isRunning || !canRunEvals}
                className={`min-w-[120px] ${isRunning ? "bg-blue-400" : "bg-blue-600 hover:bg-blue-700"}`}
              >
                {isRunning ? "运行中..." : "运行评测"}
              </Button>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-3 gap-3 border-t border-gray-100 pt-3">
              <div className="flex flex-col">
                <span className="text-sm font-medium text-gray-700">模型</span>
                <span className="text-sm text-gray-600 font-mono">{formatModelList()}</span>
              </div>
              
              <div className="flex flex-col">
                <span className="text-sm font-medium text-gray-700">技术栈</span>
                <span className="text-sm text-gray-600 font-mono">{selectedStack}</span>
              </div>
              
              <div className="flex flex-col">
                <span className="text-sm font-medium text-gray-700">输入文件</span>
                <span className="text-sm text-gray-600">已选 {selectedFiles.length} 个</span>
              </div>
            </div>
            
            <div 
              className="flex items-center gap-1 text-xs text-gray-600 cursor-pointer mt-1 hover:bg-gray-50 inline-block rounded px-2 py-1"
              onClick={() => setShowPaths(!showPaths)}
            >
              {showPaths ? <BsChevronDown size={12} /> : <BsChevronRight size={12} />}
              <span className="font-medium">路径</span>
            </div>
            
            {showPaths && (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-xs text-gray-600 mt-2 bg-gray-50 p-2 rounded-md">
                <div>
                  <span className="font-medium">输入路径：</span>
                  <code className="ml-2 bg-gray-100 px-2 py-0.5 rounded">
                    backend/evals_data/inputs
                  </code>
                </div>
                <div>
                  <span className="font-medium">输出路径：</span>
                  <code className="ml-2 bg-gray-100 px-2 py-0.5 rounded">
                    backend/evals_data/outputs
                  </code>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Selection Controls */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 max-w-5xl mx-auto">
          {/* Model Selection Section */}
          <div className="bg-white rounded-lg border border-gray-200 shadow-sm">
            <div className="border-b border-gray-200 px-4 py-3 bg-gray-50 rounded-t-lg">
              <h2 className="font-medium">选择模型</h2>
            </div>
            <div className="p-3">
              <div className="border rounded-md max-h-[300px] overflow-y-auto">
                <div className="grid grid-cols-1 divide-y divide-gray-100">
                  {models.map((model) => (
                    <div
                      key={model}
                      className={`flex items-center justify-between px-3 py-2 cursor-pointer hover:bg-gray-50 ${
                        selectedModels.includes(model)
                          ? "bg-blue-50"
                          : ""
                      }`}
                      onClick={() => handleModelToggle(model)}
                    >
                      <span className="text-sm truncate" title={model}>{model}</span>
                      {selectedModels.includes(model) ? (
                        <BsCheckLg className="h-3.5 w-3.5 text-blue-500 flex-shrink-0" />
                      ) : (
                        <div className="h-3.5 w-3.5 border rounded-sm flex-shrink-0" />
                      )}
                    </div>
                  ))}
                </div>
              </div>
              <div className="flex justify-between mt-2 text-xs">
                <p className="text-gray-500">
                  已选：{selectedModels.length} / {models.length}
                </p>
                <div className="space-x-2">
                  {selectedModels.length < models.length && (
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={handleSelectAll}
                      className="text-xs h-6 px-2 text-gray-500 hover:text-gray-700"
                    >
                      全选
                    </Button>
                  )}
                  {selectedModels.length > 0 && (
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => setSelectedModels([])}
                      className="text-xs h-6 px-2 text-gray-500 hover:text-gray-700"
                    >
                      清空
                    </Button>
                  )}
                </div>
              </div>
            </div>
          </div>

          {/* Stack Selection Section */}
          <div className="bg-white rounded-lg border border-gray-200 shadow-sm">
            <div className="border-b border-gray-200 px-4 py-3 bg-gray-50 rounded-t-lg">
              <h2 className="font-medium">选择技术栈</h2>
            </div>
            <div className="p-3">
              <select
                value={selectedStack}
                onChange={(e) => setSelectedStack(e.target.value)}
                className="w-full py-2 px-3 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
              >
                {stacks.map((stack) => (
                  <option key={stack} value={stack}>
                    {stack}
                  </option>
                ))}
              </select>
            </div>
          </div>

          {/* Input Files Section */}
          <div className="bg-white rounded-lg border border-gray-200 shadow-sm lg:col-span-1 md:col-span-2">
            <div className="border-b border-gray-200 px-4 py-3 bg-gray-50 rounded-t-lg">
              <h2 className="font-medium">选择输入文件</h2>
            </div>
            <div className="p-3">
              <InputFileSelector onFilesSelected={handleFilesSelected} />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default RunEvalsPage;

// frontend/src/components/evals/RunEvalsPage.vue
<template>
  <div>
    <EvalNavigation />

    <div class="container mx-auto px-4 py-6">
      <div class="mb-6 bg-white rounded-lg border border-gray-200 shadow-sm p-4 max-w-5xl mx-auto">
        <div class="flex flex-col gap-4">
          <div class="flex flex-wrap justify-between items-center">
            <h1 class="text-2xl font-bold">运行评测</h1>
            <button
              type="button"
              :disabled="isRunning || !canRunEvals"
              class="min-w-[120px] text-white px-4 py-2 rounded"
              :class="isRunning ? 'bg-blue-400' : 'bg-blue-600 hover:bg-blue-700'"
              @click="runEvals"
            >
              {{ isRunning ? "运行中..." : "运行评测" }}
            </button>
          </div>

          <div class="grid grid-cols-1 md:grid-cols-3 gap-3 border-t border-gray-100 pt-3">
            <div class="flex flex-col">
              <span class="text-sm font-medium text-gray-700">模型</span>
              <span class="text-sm text-gray-600 font-mono">{{ formatModelList() }}</span>
            </div>

            <div class="flex flex-col">
              <span class="text-sm font-medium text-gray-700">技术栈</span>
              <span class="text-sm text-gray-600 font-mono">{{ selectedStack }}</span>
            </div>

            <div class="flex flex-col">
              <span class="text-sm font-medium text-gray-700">输入文件</span>
              <span class="text-sm text-gray-600">已选 {{ selectedFiles.length }} 个</span>
            </div>
          </div>

          <div
            class="flex items-center gap-1 text-xs text-gray-600 cursor-pointer mt-1 hover:bg-gray-50 inline-block rounded px-2 py-1"
            @click="showPaths = !showPaths"
          >
            <svg v-if="showPaths" class="h-3 w-3" viewBox="0 0 24 24" fill="none" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7" />
            </svg>
            <svg v-else class="h-3 w-3" viewBox="0 0 24 24" fill="none" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
            </svg>
            <span class="font-medium">路径</span>
          </div>

          <div v-if="showPaths" class="grid grid-cols-1 md:grid-cols-2 gap-3 text-xs text-gray-600 mt-2 bg-gray-50 p-2 rounded-md">
            <div>
              <span class="font-medium">输入路径：</span>
              <code class="ml-2 bg-gray-100 px-2 py-0.5 rounded">backend/evals_data/inputs</code>
            </div>
            <div>
              <span class="font-medium">输出路径：</span>
              <code class="ml-2 bg-gray-100 px-2 py-0.5 rounded">backend/evals_data/outputs</code>
            </div>
          </div>
        </div>
      </div>

      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 max-w-5xl mx-auto">
        <div class="bg-white rounded-lg border border-gray-200 shadow-sm">
          <div class="border-b border-gray-200 px-4 py-3 bg-gray-50 rounded-t-lg">
            <h2 class="font-medium">选择模型</h2>
          </div>
          <div class="p-3">
            <div class="border rounded-md max-h-[300px] overflow-y-auto">
              <div class="grid grid-cols-1 divide-y divide-gray-100">
                <div
                  v-for="model in models"
                  :key="model"
                  class="flex items-center justify-between px-3 py-2 cursor-pointer hover:bg-gray-50"
                  :class="selectedModels.includes(model) ? 'bg-blue-50' : ''"
                  @click="handleModelToggle(model)"
                >
                  <span class="text-sm truncate" :title="model">{{ model }}</span>
                  <span v-if="selectedModels.includes(model)" class="text-blue-500">
                    <svg class="h-3.5 w-3.5" viewBox="0 0 24 24" fill="currentColor">
                      <path d="M20 6L9 17l-5-5 1.4-1.4L9 14.2 18.6 4.6 20 6z" />
                    </svg>
                  </span>
                  <span v-else class="h-3.5 w-3.5 border rounded-sm" />
                </div>
              </div>
            </div>
            <div class="flex justify-between mt-2 text-xs">
              <p class="text-gray-500">已选：{{ selectedModels.length }} / {{ models.length }}</p>
              <div class="space-x-2">
                <button
                  v-if="selectedModels.length < models.length"
                  type="button"
                  class="text-xs h-6 px-2 text-gray-500 hover:text-gray-700"
                  @click="handleSelectAll"
                >
                  全选
                </button>
                <button
                  v-if="selectedModels.length > 0"
                  type="button"
                  class="text-xs h-6 px-2 text-gray-500 hover:text-gray-700"
                  @click="selectedModels = []"
                >
                  清空
                </button>
              </div>
            </div>
          </div>
        </div>

        <div class="bg-white rounded-lg border border-gray-200 shadow-sm">
          <div class="border-b border-gray-200 px-4 py-3 bg-gray-50 rounded-t-lg">
            <h2 class="font-medium">选择技术栈</h2>
          </div>
          <div class="p-3">
            <select
              v-model="selectedStack"
              class="w-full py-2 px-3 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
            >
              <option v-for="stack in stacks" :key="stack" :value="stack">{{ stack }}</option>
            </select>
          </div>
        </div>

        <div class="bg-white rounded-lg border border-gray-200 shadow-sm lg:col-span-1 md:col-span-2">
          <div class="border-b border-gray-200 px-4 py-3 bg-gray-50 rounded-t-lg">
            <h2 class="font-medium">选择输入文件</h2>
          </div>
          <div class="p-3">
            <InputFileSelector @files-selected="handleFilesSelected" />
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from "vue";
import { HTTP_BACKEND_URL } from "../../config";
import InputFileSelector from "./InputFileSelector.vue";
import EvalNavigation from "./EvalNavigation.vue";

interface ModelResponse {
  models: string[];
  stacks: string[];
}

const isRunning = ref(false);
const models = ref<string[]>([]);
const stacks = ref<string[]>([]);
const selectedModels = ref<string[]>([]);
const selectedStack = ref<string>("html_tailwind");
const selectedFiles = ref<string[]>([]);
const showPaths = ref(false);

onMounted(async () => {
  const response = await fetch(`${HTTP_BACKEND_URL}/models`);
  const data: ModelResponse = await response.json();
  models.value = data.models;
  stacks.value = data.stacks;
});

onBeforeUnmount(() => {
  document.title = "截图生成代码";
});

const runEvals = async () => {
  try {
    isRunning.value = true;
    document.title = "正在运行评测...";

    const response = await fetch(`${HTTP_BACKEND_URL}/run_evals`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        models: selectedModels.value,
        stack: selectedStack.value,
        files: selectedFiles.value,
      }),
    });

    if (!response.ok) {
      throw new Error("运行评测失败");
    }

    const outputFiles = await response.json();
    console.log("Generated files:", outputFiles);

    document.title = "✓ 评测完成";
  } catch (error) {
    console.error("Error running evals:", error);
    document.title = "❌ 评测错误";
    setTimeout(() => {
      document.title = "截图生成代码";
    }, 5000);
  } finally {
    isRunning.value = false;
  }
};

const handleModelToggle = (model: string) => {
  if (selectedModels.value.includes(model)) {
    selectedModels.value = selectedModels.value.filter((m) => m !== model);
  } else {
    selectedModels.value = [...selectedModels.value, model];
  }
};

const handleSelectAll = () => {
  selectedModels.value = models.value;
};

const handleFilesSelected = (files: string[]) => {
  selectedFiles.value = files;
};

const formatModelList = () => {
  if (selectedModels.value.length === 0) return "无";
  if (selectedModels.value.length === 1) return selectedModels.value[0];
  if (selectedModels.value.length <= 2) return selectedModels.value.join(", ");
  return `${selectedModels.value.slice(0, 2).join(", ")} +${
    selectedModels.value.length - 2
  } 个`;
};

const canRunEvals = computed(
  () => selectedModels.value.length > 0 && selectedFiles.value.length > 0
);
</script>
